#!/bin/sh

VOLUME=`pamixer --get-volume`
MUTED=`pamixer --get-mute`
SINK=`pamixer --get-default-sink | awk -F'"' '$0=$4'`

case "$SINK" in
  "Tiger Lake-LP"*"Speaker + Headphones") SINK="Speakers/Headphones" ;;
  "Navi 21/23 HDMI/DP"*) SINK="Display";;
  "Starship/Matisse"*) SINK="Headphones";;
esac

if [[ "$MUTED" == "true" ]]; then
  VOLUME="Muted"
else
  VOLUME+="%"
fi

echo "$VOLUME ($SINK)"

