---
- name: Install
  kewlfft.aur.aur:
    name: ["hyprland", "xdg-desktop-portal-hyprland", "xdg-desktop-portal-gtk"]
    state: present
- name: Config
  file:
    src: "{{ roles }}/hyprland/files"
    dest: "{{ config }}/hypr"
    state: link
