---
- name: Install
  kewlfft.aur.aur:
    name: ["hyprland", "pipewire", "wireplumber", "pipewire-jack", "pipewire-alsa", "pipewire-pulse", "xdg-desktop-portal-hyprland", "xdg-desktop-portal-gtk", "polkit-kde-agent", "qt5-wayland", "qt6-wayland", "wpaperd", "satty", "grim", "slurp", "wl-screenrec", "swaylock", "swayidle", "swaybg", "wl-clipboard", "python-pywal", "network-manager-applet"]
    state: present
- name: Config
  file:
    src: "{{ roles }}/hyprland/files"
    dest: "{{ config }}/hyprland"
    state: link

- include_role:
    name: lemurs
- include_role:
    name: wmenu
- include_role:
    name: flatseal
- include_role:
    name: obsidian
- include_role:
    name: pavucontrol
- include_role:
    name: spotify
- include_role:
    name: steam
- include_role:
    name: blender
- include_role:
    name: brave
- include_role:
    name: discord
- include_role:
    name: fonts
- include_role:
    name: kitty
- include_role:
    name: libreoffice
- include_role:
    name: eww
- include_role:
    name: transmissioneww
