---
- hosts: localhost
  connection: local

  vars:
    username: "{{ ansible_user_id }}"
    home: "{{ ansible_env.HOME }}"
    config: "{{ home }}/.config"
  vars_files:
    - ./vault.yml

  pre_tasks:
    - name: "pacman : Enable Multilib"
      become: true
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
        insertafter: '^#\[multilib\]$'
        state: present
    - name: "pacman : Enable coloured output"
      become: true
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#\s*Color.*$'
        line: "Color"
    - name: "pacman : Enable ParallelDownloads and setting appropriate core count"
      become: true
      replace:
        path: /etc/pacman.conf
        regexp: ".*ParallelDownloads = .*"
        replace: "ParallelDownloads = {{ ansible_processor_vcpus + 4 }}"
    - name: "pacman : Update cache and system upgrade"
      become: true
      pacman:
        update_cache: true
        upgrade: true

  roles:
    - { name: "home", tags: ["home"] }
    - { name: "ssh", tags: ["ssh"] }
    - { name: "paru", tags: ["paru"] }
    - { name: "zsh", tags: ["zsh"] }
    - { name: "fonts", tags: ["fonts"] }

    - { name: "tmux", tags: ["tmux"] }

    - { name: "flatpak", tags: ["flatpak"] }
    - { name: "floorp", tags: ["floorp"] }

    - { name: "wayland", tags: ["wayland"] }
    - { name: "pywal", tags: ["pywal"] }
    - { name: "pipewire", tags: ["pipewire"] }
    - { name: "hyprland", tags: ["hyprland"] }
    - { name: "waybar", tags: ["waybar"] }
    - { name: "kitty", tags: ["kitty"] }
    - { name: "discord", tags: ["discord"] }
    - { name: "element", tags: ["element"] }
    - { name: "scripts", tags: ["scripts"] }
    - { name: "rofi", tags: ["rofi"] }
    - { name: "mako", tags: ["mako"] }
    - { name: "theming", tags: ["theming"] }
    - { name: "polkit", tags: ["polkit"] }
    - { name: "node", tags: ["node"] }
    - { name: "git", tags: ["git"] }
    - { name: "ufw", tags: ["ufw"] }

    - { name: "steam", tags: ["steam"] }
    - { name: "rust", tags: ["rust"] }
    - { name: "proton", tags: ["proton"] }
    - { name: "obsidian", tags: ["obsidian"] }
    - { name: "nextcloud", tags: ["nextcloud"] }
    - { name: "minecraft", tags: ["minecraft"] }
    - { name: "man", tags: ["man"] }
    - { name: "flatseal", tags: ["flatseal"] }
    - { name: "bluetooth", tags: ["bluetooth"] }
    - { name: "blender", tags: ["blender"] }
    - { name: "wl-clipboard", tags: ["wl-clipboard"] }
    - { name: "vimv", tags: ["vimv"] }
    - { name: "unzip", tags: ["unzip"] }
    - { name: "transmission", tags: ["transmission"] }
    - { name: "nvim", tags: ["nvim"] }
