---
- hosts: localhost
  connection: local

  vars:
    username: "{{ ansible_user_id }}"
    home: "{{ ansible_env.HOME }}"
  vars_files:
    - ./vault.yml

  pre_tasks:
    - name: "pacman : Enable Multilib"
      become: true
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
        insertafter: '^#\[multilib\]$'
        state: present
    - name: "pacman : Enable coloured output"
      become: true
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#\s*Color.*$'
        line: "Color"
    - name: "pacman : Enable ParallelDownloads and setting appropriate core count"
      become: true
      replace:
        path: /etc/pacman.conf
        regexp: ".*ParallelDownloads = .*"
        replace: "ParallelDownloads = {{ ansible_processor_vcpus + 4 }}"
    - name: "pacman : Update cache and system upgrade"
      become: true
      pacman:
        update_cache: true
        upgrade: true

  roles:
    - { name: "home", tags: ["home"] }
    - { name: "ssh", tags: ["ssh"] }
    - { name: "gpg", tags: ["gpg"] }
    - { name: "paru", tags: ["paru"] }
    - { name: "zsh", tags: ["zsh"] }
