---
- hosts: localhost
  connection: local

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    config: "{{ home }}/.config"
    username: "{{ ansible_user_id }}"
  vars_files:
    - ./vault

  pre_tasks:
    - name: "pacman : Enable Multilib"
      become: true
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
        insertafter: '^#\[multilib\]$'
        state: present
    - name: "pacman : Enable coloured output"
      become: true
      lineinfile:
        path: /etc/pacman.conf
        regexp: '^#\s*Color.*$'
        line: "Color"
    - name: "pacman : Enable ParallelDownloads and setting appropriate core count"
      become: true
      replace:
        path: /etc/pacman.conf
        regexp: ".*ParallelDownloads = .*"
        replace: "ParallelDownloads = {{ ansible_processor_vcpus + 4 }}"
    - name: "pacman : Update cache and system upgrade"
      become: true
      pacman:
        update_cache: true
        upgrade: true

  roles:
    - { name: home, tags: ["home"] }

    - { name: paru, tags: ["paru"] }
    - { name: ssh, tags: ["ssh"] }
    - { name: zsh, tags: ["zsh"] }
    - { name: node, tags: ["node"] }
    - { name: rust, tags: ["rust"] }
    - { name: nvim, tags: ["nvim"] }
    - { name: fonts, tags: ["fonts"] }
    - { name: man, tags: ["man"] }
    - { name: tmux, tags: ["tmux"] }
    - { name: flatpak, tags: ["flatpak"] }

    - { name: sway, tags: ["sway"] }
    - { name: i3blocks, tags: ["i3blocks"] }
    - { name: kitty, tags: ["kitty"] }
    - { name: librewolf, tags: ["librewolf"] }

    - { name: discord, tags: ["discord"] }
    - { name: element, tags: ["element"] }
    - { name: blender, tags: ["blender"] }
    - { name: flatseal, tags: ["flatseal"] }
    - { name: git, tags: ["git"] }
    - { name: joshuto, tags: ["joshuto"] }
    - { name: lemurs, tags: ["lemurs"] }
    - { name: onlyoffice, tags: ["onlyoffice"] }
    - { name: mako, tags: ["mako"] }
    - { name: obsidian, tags: ["obsidian"] }
    - { name: pavucontrol, tags: ["pavucontrol"] }
    - { name: pipewire, tags: ["pipewire"] }
    - { name: polkit, tags: ["polkit"] }
    - { name: tidal, tags: ["tidal"] }
    - { name: steam, tags: ["steam"] }
    - { name: transmission, tags: ["transmission"] }
    - { name: ufw, tags: ["ufw"] }
    - { name: unzip, tags: ["unzip"] }
    - { name: vimv, tags: ["vimv"] }
    - { name: wayland, tags: ["wayland"] }
    - { name: wl-clipboard, tags: ["wl-clipboard"] }
    - { name: bluetooth, tags: ["bluetooth"] }
    - { name: theming, tags: ["theming"] }
    - { name: nextcloud, tags: ["nextcloud"] }
    - { name: logind, tags: ["logind"] }
    - { name: proton, tags: ["proton"] }
