---
- name: Create logind.conf.d
  become: true
  file:
    path: /etc/systemd/logind.conf.d
    state: directory
- name: Add logind.conf
  become: true
  template:
    src: 10-general.conf.j2
    dest: /etc/systemd/logind.conf.d/10-general.conf
