---
- name: Install
  become: true
  pacman:
    name: ["i3blocks", "sysstat", "acpi"]
    state: present
- name: Config
  file:
    src: "{{ role_path }}/files/"
    dest: "{{ config }}/i3blocks"
    state: link
