mouse_support = false
scroll_offset = 10
xdg_open = true
xdg_open_fork = true

custom_commands = [
]

[display]
collapse_preview = false
column_ratio = [1, 3, 4]
show_hidden = true
line_number_style = "relative"

[preview]
# preview_script = "~/.config/joshuto/preview_file.sh"

[search]
string_case_sensitivity = "insensitive"
glob_case_sensitivity = "insensitive"
regex_case_sensitivity = "insensitive"
fzf_case_sensitivity = "insensitive"

[cmd_aliases]
# q = "quit"
# ...

[tab]
home_page = "home"

