mouse_support = false
focus_on_create = true
use_trash = true
watch_files = true
xdg_open = true
xdg_open_fork = true
case_insensitive_ext = true
zoxide_update = false

custom_commands = []

[display]
mode = "default"

automatically_count_files = true
collapse_preview = true
column_ratio = [1, 3, 4]
scroll_offset = 10
show_borders = true
show_hidden = true
show_icons = true
line_number_style = "relative"

linemode = "size"

[display.sort]
sort_method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
max_preview_size = 671100000

[search]
string_case_sensitivity = "insensitive"
glob_case_sensitivity = "sensitive"
regex_case_sensitivity = "sensitive"
fzf_case_sensitivity = "insensitive"

[tab]
home_page = "inherit"
