---
- name: Install
  become: true
  pacman:
    name: ["zsh", "bat", "eza", "btop", "less"]
    state: present
- name: Config
  template:
    src: ".zshrc.j2"
    dest: "{{ home }}/.zshrc"
- name: Change root shell
  become: true
  user:
    name: "root"
    shell: "/bin/zsh"
- name: Change user's shell
  become: true
  user:
    name: "{{ username }}"
    shell: "/bin/zsh"
