---
- name: Setup user home directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ home }}/.config"
    - "{{ home }}/Documents"
    - "{{ home }}/Downloads"
    - "{{ home }}/Music"
    - "{{ home }}/Pictures"
    - "{{ home }}/Videos"
    - "{{ home }}/Documents/Personal"
    - "{{ home }}/Documents/College"
    - "{{ home }}/Documents/Work"
