---
- name: Install
  become: true
  flatpak:
    name: com.spotify.Client
    state: present

- name: Check if adblock is installed
  stat:
    path: "{{ home }}/.spotify-adblock"
  register: adblock_check
- name: Clone adblock
  git:
    repo: "https://github.com/abba23/spotify-adblock.git"
    dest: "{{ home }}/spotify-adblock"
  when: adblock_check.stat.exists == False
- name: Make adblock
  shell:
    cmd: "make"
  args:
    chdir: "{{ home }}/spotify-adblock"
  when: adblock_check.stat.exists == False
- name: Install adblock
  become: true
  shell:
    cmd: "make install"
  args:
    chdir: "{{ home }}/spotify-adblock"
  when: adblock_check.stat.exists == False
- name: Create adblock directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ home }}/.spotify-adblock"
    - "{{ home }}/.config/spotify-adblock"
  when: adblock_check.stat.exists == False
- name: Copy adblock files
  copy:
    src: "{{ home }}/spotify-adblock/target/release/libspotifyadblock.so"
    dest: "{{ home }}/.spotify-adblock/spotify-adblock.so"
  when: adblock_check.stat.exists == False
- name: Copy adblock config file
  copy:
    src: "{{ home }}/spotify-adblock/config.toml"
    dest: "{{ home }}/.config/spotify-adblock/config.toml"
  when: adblock_check.stat.exists == False
- name: Add adblock directories to Spotify Flatpak filesystems
  shell: flatpak override --user --filesystem="~/.spotify-adblock/spotify-adblock.so" --filesystem="~/.config/spotify-adblock/config.toml" com.spotify.Client
  when: adblock_check.stat.exists == False
- name: Add spotify-adblock script to /usr/local/bin
  become: true
  template:
    src: spotify-adblock.j2
    dest: /usr/local/bin/spotify-adblock
    mode: +x
  when: adblock_check.stat.exists == False
- name: Remove the adblock directory after installation
  ansible.builtin.file:
    path: "{{ home }}/spotify-adblock"
    state: absent
  when: adblock_check.stat.exists == False
