windowrulev2 = workspace 1, class:(kitty)
windowrulev2 = workspace 2, class:(Brave-browser)
windowrulev2 = workspace 3, class:(obsidian)

windowrulev2 = workspace 9, class:(Spotify)
windowrulev2 = workspace 9, class:(cider)
windowrulev2 = workspace 10, class:(discord)

exec-once = eww o bar || $HOME/eww/target/release/eww o bar

exec-once = kitty
exec-once = flatpak run com.brave.Browser
exec-once = flatpak run md.obsidian.Obsidian

exec-once = /usr/local/bin/spotify-adblock
exec-once = cider
exec-once = flatpak run com.discordapp.Discord

