$mainMod = SUPER
$terminal = kitty
$menu = dmenu_run | wmenu
$scripts = ~/.config/hypr/scripts
$screenshot = $scripts/screenshot.sh

# MISC. ---------------------- #
bind = $mainMod,        D,      exec, $menu
bind = $mainMod,        Return, exec, $terminal
bind = $mainMod,        M,      exit

# Screenshot
bind = ALT Shift, 1, exec, $screenshot selection
bind = ALT Shift, 2, exec, $screenshot window
bind = ALT Shift, 3, exec, $screenshot screen

# WINDOW CONTROLS ------------ #
bind = $mainMod Shift,  Q,      killactive
bind = $mainMod Shift,  Space,  togglefloating

# Move focus 
bind = $mainMod, left,  movefocus, l
bind = $mainMod, down,  movefocus, d
bind = $mainMod, up,    movefocus, u
bind = $mainMod, right, movefocus, r

# ... with hjkl
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# Move window
bind = $mainMod Shift, left,    movewindow, l
bind = $mainMod Shift, down,    movewindow, d
bind = $mainMod Shift, up,      movewindow, u
bind = $mainMod Shift, right,   movewindow, r

# ... with hjkl
bind = $mainMod Shift, H, movewindow, l
bind = $mainMod Shift, J, movewindow, d
bind = $mainMod Shift, K, movewindow, u
bind = $mainMod Shift, L, movewindow, r

# WORKSPACE CONTROLS --------- #
# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Move/resize windows with Mod + LMB/RMB + Drag
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
