input {
    kb_layout = gb
    kb_options = caps:escape

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = no
    }
}

device:usb-optical-mouse- {
    sensitivity = -0.25
}

gestures {
    workspace_swipe = off
}
