---
- name: Install
  become: true
  flatpak:
    name: dev.vencord.Vesktop
    state: present
- name: Flatpak permissions
  become: true
  shell: flatpak override dev.vencord.Vesktop "{{ item }}"
  with_items:
    - "--filesystem=~/Downloads"
