---
- name: Install
  become: true
  pacman:
    name: tmux
    state: present
- name: Directory
  file:
    path: "{{ config }}/tmux"
    state: directory
- name: Config
  template:
    src: tmux.conf.j2
    dest: "{{ config }}/tmux/tmux.conf"
