---
- name: Install
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      [
        "sway",
        "swaybg",
        "swaylock",
        "swayidle",
        "i3blocks",
        "autotiling",
        "wmenu",
        "dmenu",
        "network-manager-applet",
        "pipewire",
        "pipewire-jack",
        "pipewire-alsa",
        "pipewire-pulse",
        "xdg-desktop-portal-wlr",
        "xdg-desktop-portal-gnome",
        "brightnessctl",
        "pamixer",
      ]
    state: present
- name: Config
  file:
    src: "{{ role_path }}/files/"
    dest: "{{ config }}/sway"
    state: link
- name: Enable Pipewire Pulse
  systemd:
    name: pipewire-pulse
    state: started
    scope: user
