---
- name: Ensure `~/.gnupg` exists
  file:
    path: "{{ home }}/.gnupg"
    state: directory
    mode: '0700'
- name: Start GPG agent
  command: gpgconf --launch gpg-agent
  environment:
    GNUPGHOME: "{{ home }}/.gnupg"
- name: Public key
  shell: echo "{{ gpg.key.public }}" | gpg --batch --import
  args:
    executable: /bin/bash
  environment:
    GNUPGHOME: "{{ home }}/.gnupg"
  register: import_public_key
  changed_when: "'public key imported' in import_public_key.stdout"
- name: Private key
  shell: echo "{{ gpg.key.private }}" | gpg --batch --import
  args:
    executable: /bin/bash
  environment:
    GNUPGHOME: "{{ home }}/.gnupg"
  register: import_private_key
  changed_when: "'private key imported' in import_private_key.stdout"
